FROM azul/zulu-openjdk:21-latest
COPY . /data/
RUN /data/src/scripts/setup.sh && cd /data && ./exploded.sh -b
COPY src/scripts/entrypoint-exploded.sh /data/entrypoint.sh

ENTRYPOINT /data/entrypoint.sh