FROM bellsoft/liberica-openjdk-debian:21.0.1
COPY . /data/
RUN /data/src/scripts/setup.sh && cd /data && ./exploded.sh -b
COPY src/scripts/entrypoint-exploded.sh /data/entrypoint.sh

ENTRYPOINT /data/entrypoint.sh