FROM container-registry.oracle.com/graalvm/native-image:17-ol8 AS builder
WORKDIR /build
COPY . /build
RUN microdnf install findutils
RUN ./gradlew nativeCompile

FROM ubuntu:focal
EXPOSE 8080
COPY --from=builder /build/build/native/nativeCompile/spring-petclinic spring-petclinic
ENTRYPOINT ["/spring-petclinic"]
